image_path: "demo/bugatti_veyron_lamborghini.jpg"
image_caption: ['Bugatti Veyron', 'Lamborghini']

clip:
  semantic_clip_model_name: 'ViT-L/14'
  semantic_pretrained_data: 'openai'
  clip_model_name: 'ViT-B/16'
  pretrained_data: 'openai'

camcut:
  iom_thres: 0.6
  mask_threshold: 0.5
  confidence_threshold: 0
  clipes_threshold: 0.7
  visual_prompt_type: ['gray', 'blur']
  semantic_templates: ['a clean origami {}.',
                        'a photo of a {}.',
                    'This is a photo of a {}',
                    'There is a {} in the scene',
                    'There is the {} in the scene',
                    'a photo of a {} in the scene',
                    'a photo of a small {}.',
                    'a photo of a medium {}.',
                    'a photo of a large {}.',
                    'This is a photo of a small {}.',
                    'This is a photo of a medium {}.',
                    'This is a photo of a large {}.',
                    'There is a small {} in the scene.',
                    'There is a medium {} in the scene.',
                    'There is a large {} in the scene.']
  bg_cls: ['ground', 'land', 'grass', 'tree', 'building',
            'wall', 'sky', 'lake', 'water', 'river', 'sea',
            'railway', 'railroad', 'helmet', 'cloud', 'house',
            'mountain', 'ocean', 'road', 'rock', 'street',
            'valley', 'bridge']

sam:
  model_dir: "//homes/55/runjia/scratch/SAM/model_dir"
  sam_checkpoint: "/homes/55/runjia/scratch/SAM/model_dir/sam_hq_vit_h.pth"  #  "/storage2/jianhaoy/SAM/sam_hq_vit_h.pth"
  model_type: "vit_h"
  min_pred_threshold: 0.1
  points_per_side: 64
  pred_iou_thresh: 0.88
  stability_score_thresh: 0.9
  box_nms_thresh: 0.7

test:
  seg_mode: "semantic"
  use_pseudo: False