# image_path: "/homes/55/runjia/scratch/COCO_stuff/images/val2017/000000222863.jpg"
# image_caption: ["cow"]
# ann_path: /homes/55/runjia/scratch/COCO_stuff/annotations/val2017/000000222863_instanceTrainIds.png

# image_path: "/homes/55/runjia/scratch/COCO_stuff/images/val2017/000000397639.jpg"
# image_caption: ["sheep"]
# ann_path: /homes/55/runjia/scratch/COCO_stuff/annotations/val2017/000000397639_instanceTrainIds.png

# image_path: "/homes/55/runjia/scratch/COCO_stuff/images/val2017/000000049259.jpg"
# image_caption: ["person", "stop sign"]

# image_path: "/homes/55/runjia/scratch/COCO_stuff/images/val2017/000000157847.jpg"
# image_caption: ["bird"]
# ann_path: /homes/55/runjia/scratch/COCO_stuff/annotations/val2017/000000157847_instanceTrainIds.png

# image_path: "/homes/55/runjia/scratch/COCO_stuff/images/val2017/000000442306.jpg"
# image_caption: ['person', 'umbrella']
# ann_path: /homes/55/runjia/scratch/COCO_stuff/annotations/val2017/000000442306_instanceTrainIds.png

# image_path: "/homes/55/runjia/scratch/COCO_stuff/images/val2017/000000031322.jpg"
# image_caption: ['bird']
# ann_path: /homes/55/runjia/scratch/COCO_stuff/annotations/val2017/000000031322_instanceTrainIds.png


clip:
  semantic_clip_model_name: 'ViT-L/14'
  semantic_pretrained_data: 'openai'
  clip_model_name: "ViT-B/16"
  pretrained_data: 'openai'


camcut:
  iom_thres: 0.6
  mask_threshold: 0.5
  min_area_ratio: 0.2
  num_iteration: 1
  confidence_threshold: 0 # 0.2
  clipes_threshold: 0.5
  visual_prompt_type: ['blur', 'gray']
  semantic_templates: ['a clean origami {}.',
                        'a photo of a {}.',
                    'This is a photo of a {}',
                    'There is a {} in the scene',
                    'There is the {} in the scene',
                    'a photo of a {} in the scene',
                    'a photo of a small {}.',
                    'a photo of a medium {}.',
                    'a photo of a large {}.',
                    'This is a photo of a small {}.',
                    'This is a photo of a medium {}.',
                    'This is a photo of a large {}.',
                    'There is a small {} in the scene.',
                    'There is a medium {} in the scene.',
                    'There is a large {} in the scene.']
  bg_cls: ['ground', 'land', 'grass', 'tree', 'building',
            'wall', 'sky', 'lake', 'water', 'river', 'sea',
            'railway', 'railroad', 'helmet', 'cloud', 'house',
            'mountain', 'ocean', 'road', 'rock', 'street',
            'valley', 'bridge']
                    
sam:
  model_dir: "//homes/55/runjia/scratch/SAM/model_dir"
  sam_checkpoint: "/homes/55/runjia/scratch/SAM/model_dir/sam_hq_vit_h.pth"  #  "/storage2/jianhaoy/SAM/sam_hq_vit_h.pth"
  model_type: "vit_h"
  min_pred_threshold: 0.01
  points_per_side: 64
  pred_iou_thresh: 0.88
  stability_score_thresh: 0.95
  box_nms_thresh: 0.7
  matching_thresh: 0.7

test:
  algo: "maskcut"
  ds_name: "cocostuff"
  seg_mode: "semantic"
  data_root: "/homes/55/runjia/scratch/COCO_stuff"
  sam_mask_root: "/homes/55/runjia/scratch/SAM_masks/COCOSTUFF"
  output_path: "./outputs/"
  use_pseudo: False
  split: "val"
  n_class: 81
  num_chunks: 1
  chunk_index: 0

save_path: "./outputs"